import { Country } from './types';


export const countryInformation: Country[] = [
  {
    iso2: 'AD',
    name: 'Andorra',
    native: 'Andorra',
    dialCode: '376',
    continent_name: 'EU',
  },
  {
    iso2: 'AE',
    name: 'United Arab Emirates',
    native: 'دولة الإمارات العربية المتحدة',
    dialCode: '971',
    continent_name: 'AS',
  },
  {
    iso2: 'AF',
    name: 'Afghanistan',
    native: 'افغانستان',
    dialCode: '93',
    continent_name: 'AS',
  },
  {
    iso2: 'AG',
    name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'AI',
    name: 'Anguilla',
    native: 'Anguilla',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'AL',
    name: 'Albania',
    native: 'Shqipëria',
    dialCode: '355',
    continent_name: 'EU',
  },
  {
    iso2: 'AM',
    name: 'Armenia',
    native: 'Հայաստան',
    dialCode: '374',
    continent_name: 'AS',
  },
  {
    iso2: 'AO',
    name: 'Angola',
    native: 'Angola',
    dialCode: '244',
    continent_name: 'AF',
  },
  {
    iso2: 'AR',
    name: 'Argentina',
    native: 'Argentina',
    dialCode: '54',
    continent_name: 'SA',
  },
  {
    iso2: 'AS',
    name: 'American Samoa',
    native: 'American Samoa',
    dialCode: '1',
    continent_name: 'OC',
  },
  {
    iso2: 'AT',
    name: 'Austria',
    native: 'Österreich',
    dialCode: '43',
    continent_name: 'EU',
  },
  {
    iso2: 'AU',
    name: 'Australia',
    native: 'Australia',
    dialCode: '61',
    continent_name: 'OC',
  },
  {
    iso2: 'AW',
    name: 'Aruba',
    native: 'Aruba',
    dialCode: '297',
    continent_name: 'NA',
  },
  {
    iso2: 'AX',
    name: 'Åland Islands',
    dialCode: '358',
    native: 'Suomi',
    continent_name: 'EU',
  },
  {
    iso2: 'AZ',
    name: 'Azerbaijan',
    native: 'Azərbaycan',
    dialCode: '994',
    continent_name: 'AS',
  },
  {
    iso2: 'BA',
    name: 'Bosnia and Herzegovina',
    native: 'Bosna i Hercegovina',
    dialCode: '387',
    continent_name: 'EU',
  },
  {
    iso2: 'BB',
    name: 'Barbados',
    native: 'Barbados',
    dialCode: '1246',
    continent_name: 'NA',
  },
  {
    iso2: 'BD',
    name: 'Bangladesh',
    native: 'Bangladesh',
    dialCode: '880',
    continent_name: 'AS',
  },
  {
    iso2: 'BE',
    name: 'Belgium',
    native: 'België',
    dialCode: '32',
    continent_name: 'EU',
  },
  {
    iso2: 'BF',
    name: 'Burkina Faso',
    native: 'Burkina Faso',
    dialCode: '226',
    continent_name: 'AF',
  },
  {
    iso2: 'BG',
    name: 'Bulgaria',
    native: 'България',
    dialCode: '359',
    continent_name: 'EU',
  },
  {
    iso2: 'BH',
    name: 'Bahrain',
    native: '‏البحرين',
    dialCode: '973',
    continent_name: 'AS',
  },
  {
    iso2: 'BI',
    name: 'Burundi',
    native: 'Burundi',
    dialCode: '257',
    continent_name: 'AF',
  },
  {
    iso2: 'BJ',
    name: 'Benin',
    native: 'Bénin',
    dialCode: '229',
    continent_name: 'AF',
  },
  {
    iso2: 'BL',
    name: 'Saint Barthélemy',
    native: 'Saint-Barthélemy',
    dialCode: '590',
    continent_name: 'NA',
  },
  {
    iso2: 'BM',
    name: 'Bermuda',
    native: 'Bermuda',
    dialCode: '1441',
    continent_name: 'NA',
  },
  {
    iso2: 'BN',
    name: 'Brunei Darussalam',
    dialCode: '673',
    native: 'Negara Brunei Darussalam',
    continent_name: 'AS',
  },
  {
    iso2: 'BO',
    name: 'Bolivia, Plurinational State of',
    dialCode: '591',
    native: 'Bolivia',
    continent_name: 'SA',
  },
  {
    iso2: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    dialCode: '599',
    native: 'Bonaire',
    continent_name: 'NA',
  },
  {
    iso2: 'BR',
    name: 'Brazil',
    native: 'Brasil',
    dialCode: '55',
    continent_name: 'SA',
  },
  {
    iso2: 'BS',
    name: 'Bahamas',
    native: 'Bahamas',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'BT',
    name: 'Bhutan',
    native: 'ʼbrug-yul',
    dialCode: '975',
    continent_name: 'AS',
  },
  {
    iso2: 'BW',
    name: 'Botswana',
    native: 'Botswana',
    dialCode: '267',
    continent_name: 'AF',
  },
  {
    iso2: 'BY',
    name: 'Belarus',
    native: 'Белару́сь',
    dialCode: '375',
    continent_name: 'EU',
  },
  {
    iso2: 'BZ',
    name: 'Belize',
    native: 'Belize',
    dialCode: '501',
    continent_name: 'NA',
  },
  {
    iso2: 'CA',
    name: 'Canada',
    native: 'Canada',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'CC',
    name: 'Cocos (Keeling) Islands',
    dialCode: '61',
    native: 'Heard Island and McDonald Islands',
    continent_name: 'AN',
  },
  {
    iso2: 'CD',
    name: 'Congo, Democratic Republic of the',
    dialCode: '243',
    native: 'République démocratique du Congo',
    continent_name: 'AF',
  },
  {
    iso2: 'CF',
    name: 'Central African Republic',
    native: 'Ködörösêse tî Bêafrîka',
    dialCode: '236',
    continent_name: 'AF',
  },
  {
    iso2: 'CG',
    name: 'Congo',
    dialCode: '242',
    native: 'République du Congo',
    continent_name: 'AF',
  },
  {
    iso2: 'CH',
    name: 'Switzerland',
    native: 'Schweiz',
    dialCode: '41',
    continent_name: 'EU',
  },
  {
    iso2: 'CI',
    name: "Côte d'Ivoire",
    dialCode: '225',
    native: "Côte d'Ivoire",
    continent_name: 'AF',
  },
  {
    iso2: 'CK',
    name: 'Cook Islands',
    native: 'Cook Islands',
    dialCode: '682',
    continent_name: 'OC',
  },
  {
    iso2: 'CL',
    name: 'Chile',
    native: 'Chile',
    dialCode: '56',
    continent_name: 'SA',
  },
  {
    iso2: 'CM',
    name: 'Cameroon',
    native: 'Cameroon',
    dialCode: '237',
    continent_name: 'AF',
  },
  {
    iso2: 'CN',
    name: 'China',
    native: '中国',
    dialCode: '86',
    continent_name: 'AS',
  },
  {
    iso2: 'CO',
    name: 'Colombia',
    native: 'Colombia',
    dialCode: '57',
    continent_name: 'SA',
  },
  {
    iso2: 'CR',
    name: 'Costa Rica',
    native: 'Costa Rica',
    dialCode: '506',
    continent_name: 'NA',
  },
  {
    iso2: 'CU',
    name: 'Cuba',
    native: 'Cuba',
    dialCode: '53',
    continent_name: 'NA',
  },
  {
    iso2: 'CV',
    name: 'Cabo Verde',
    dialCode: '238',
    native: 'Cabo Verde',
    continent_name: 'AF',
  },
  {
    iso2: 'CW',
    name: 'Curaçao',
    dialCode: '599',
    native: 'Curaçao',
    continent_name: 'NA',
  },
  {
    iso2: 'CX',
    name: 'Christmas Island',
    native: 'Christmas Island',
    dialCode: '61',
    continent_name: 'AS',
  },
  {
    iso2: 'CY',
    name: 'Cyprus',
    native: 'Κύπρος',
    dialCode: '357',
    continent_name: 'EU',
  },
  {
    iso2: 'CZ',
    name: 'Czechia',
    dialCode: '420',
    native: 'Česká republika',
    continent_name: 'EU',
  },
  {
    iso2: 'DE',
    name: 'Germany',
    native: 'Deutschland',
    dialCode: '49',
    continent_name: 'EU',
  },
  {
    iso2: 'DJ',
    name: 'Djibouti',
    native: 'Djibouti',
    dialCode: '253',
    continent_name: 'AF',
  },
  {
    iso2: 'DK',
    name: 'Denmark',
    native: 'Danmark',
    dialCode: '45',
    continent_name: 'EU',
  },
  {
    iso2: 'DM',
    name: 'Dominica',
    native: 'Dominica',
    dialCode: '1767',
    continent_name: 'NA',
  },
  {
    iso2: 'DO',
    name: 'Dominican Republic',
    native: 'República Dominicana',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'DZ',
    name: 'Algeria',
    native: 'الجزائر',
    dialCode: '213',
    continent_name: 'AF',
  },
  {
    iso2: 'EC',
    name: 'Ecuador',
    native: 'Ecuador',
    dialCode: '593',
    continent_name: 'SA',
  },
  {
    iso2: 'EE',
    name: 'Estonia',
    native: 'Eesti',
    dialCode: '372',
    continent_name: 'EU',
  },
  {
    iso2: 'EG',
    name: 'Egypt',
    native: 'مصر‎',
    dialCode: '20',
    continent_name: 'AF',
  },
  {
    iso2: 'EH',
    name: 'Western Sahara',
    native: 'الصحراء الغربية',
    dialCode: '212',
    continent_name: 'AF',
  },
  {
    iso2: 'ER',
    name: 'Eritrea',
    native: 'ኤርትራ',
    dialCode: '291',
    continent_name: 'AF',
  },
  {
    iso2: 'ES',
    name: 'Spain',
    native: 'España',
    dialCode: '34',
    continent_name: 'EU',
  },
  {
    iso2: 'ET',
    name: 'Ethiopia',
    native: 'ኢትዮጵያ',
    dialCode: '251',
    continent_name: 'AF',
  },
  {
    iso2: 'FI',
    name: 'Finland',
    native: 'Suomi',
    dialCode: '358',
    continent_name: 'EU',
  },
  {
    iso2: 'FJ',
    name: 'Fiji',
    native: 'Fiji',
    dialCode: '679',
    continent_name: 'OC',
  },
  {
    iso2: 'FK',
    name: 'Falkland Islands (Malvinas)',
    dialCode: '500',
    native: 'Falkland Islands',
    continent_name: 'SA',
  },
  {
    iso2: 'FM',
    name: 'Micronesia, Federated States of',
    dialCode: '691',
    native: 'Micronesia',
    continent_name: 'OC',
  },
  {
    iso2: 'FO',
    name: 'Faroe Islands',
    native: 'Føroyar',
    dialCode: '298',
    continent_name: 'EU',
  },
  {
    iso2: 'FR',
    name: 'France',
    native: 'France',
    dialCode: '33',
    continent_name: 'EU',
  },
  {
    iso2: 'GA',
    name: 'Gabon',
    native: 'Gabon',
    dialCode: '241',
    continent_name: 'AF',
  },
  {
    iso2: 'GB',
    name: 'United Kingdom of Great Britain and Northern Ireland',
    dialCode: '44',
    native: 'United Kingdom',
    continent_name: 'EU',
  },
  {
    iso2: 'GD',
    name: 'Grenada',
    native: 'Grenada',
    dialCode: '1473',
    continent_name: 'NA',
  },
  {
    iso2: 'GE',
    name: 'Georgia',
    native: 'საქართველო',
    dialCode: '995',
    continent_name: 'AS',
  },
  {
    iso2: 'GF',
    name: 'French Guiana',
    native: 'Guyane française',
    dialCode: '594',
    continent_name: 'SA',
  },
  {
    iso2: 'GG',
    name: 'Guernsey',
    native: 'Guernsey',
    dialCode: '44',
    continent_name: 'EU',
  },
  {
    iso2: 'GH',
    name: 'Ghana',
    native: 'Ghana',
    dialCode: '233',
    continent_name: 'AF',
  },
  {
    iso2: 'GI',
    name: 'Gibraltar',
    native: 'Gibraltar',
    dialCode: '350',
    continent_name: 'EU',
  },
  {
    iso2: 'GL',
    name: 'Greenland',
    native: 'Kalaallit Nunaat',
    dialCode: '299',
    continent_name: 'NA',
  },
  {
    iso2: 'GM',
    name: 'Gambia',
    native: 'Gambia',
    dialCode: '220',
    continent_name: 'AF',
  },
  {
    iso2: 'GN',
    name: 'Guinea',
    native: 'Guinée',
    dialCode: '224',
    continent_name: 'AF',
  },
  {
    iso2: 'GP',
    name: 'Guadeloupe',
    native: 'Guadeloupe',
    dialCode: '590',
    continent_name: 'NA',
  },
  {
    iso2: 'GQ',
    name: 'Equatorial Guinea',
    native: 'Guinea Ecuatorial',
    dialCode: '240',
    continent_name: 'AF',
  },
  {
    iso2: 'GR',
    name: 'Greece',
    native: 'Ελλάδα',
    dialCode: '30',
    continent_name: 'EU',
  },
  {
    iso2: 'GT',
    name: 'Guatemala',
    native: 'Guatemala',
    dialCode: '502',
    continent_name: 'NA',
  },
  {
    iso2: 'GU',
    name: 'Guam',
    native: 'Guam',
    dialCode: '1671',
    continent_name: 'OC',
  },
  {
    iso2: 'GW',
    name: 'Guinea-Bissau',
    native: 'Guiné-Bissau',
    dialCode: '245',
    continent_name: 'AF',
  },
  {
    iso2: 'GY',
    name: 'Guyana',
    native: 'Guyana',
    dialCode: '592',
    continent_name: 'SA',
  },
  {
    iso2: 'HK',
    name: 'Hong Kong',
    native: '香港',
    dialCode: '852',
    continent_name: 'AS',
  },
  {
    iso2: 'HN',
    name: 'Honduras',
    native: 'Honduras',
    dialCode: '504',
    continent_name: 'NA',
  },
  {
    iso2: 'HR',
    name: 'Croatia',
    native: 'Hrvatska',
    dialCode: '385',
    continent_name: 'EU',
  },
  {
    iso2: 'HT',
    name: 'Haiti',
    native: 'Haïti',
    dialCode: '509',
    continent_name: 'NA',
  },
  {
    iso2: 'HU',
    name: 'Hungary',
    native: 'Magyarország',
    dialCode: '36',
    continent_name: 'EU',
  },
  {
    iso2: 'ID',
    name: 'Indonesia',
    native: 'Indonesia',
    dialCode: '62',
    continent_name: 'AS',
  },
  {
    iso2: 'IE',
    name: 'Ireland',
    native: 'Éire',
    dialCode: '353',
    continent_name: 'EU',
  },
  {
    iso2: 'IL',
    name: 'Israel',
    native: 'יִשְׂרָאֵל',
    dialCode: '972',
    continent_name: 'AS',
  },
  {
    iso2: 'IM',
    name: 'Isle of Man',
    native: 'Isle of Man',
    dialCode: '44',
    continent_name: 'EU',
  },
  {
    iso2: 'IN',
    name: 'India',
    native: 'भारत',
    dialCode: '91',
    continent_name: 'AS',
  },
  {
    iso2: 'IO',
    name: 'British Indian Ocean Territory',
    native: 'British Indian Ocean Territory',
    dialCode: '246',
    continent_name: 'AS',
  },
  {
    iso2: 'IQ',
    name: 'Iraq',
    native: 'العراق',
    dialCode: '964',
    continent_name: 'AS',
  },
  {
    iso2: 'IR',
    name: 'Iran, Islamic Republic of',
    dialCode: '98',
    native: 'ایران',
    continent_name: 'AS',
  },
  {
    iso2: 'IS',
    name: 'Iceland',
    native: 'Ísland',
    dialCode: '354',
    continent_name: 'EU',
  },
  {
    iso2: 'IT',
    name: 'Italy',
    native: 'Italia',
    dialCode: '39',
    continent_name: 'EU',
  },
  {
    iso2: 'JE',
    name: 'Jersey',
    native: 'Jersey',
    dialCode: '44',
    continent_name: 'EU',
  },
  {
    iso2: 'JM',
    name: 'Jamaica',
    native: 'Jamaica',
    dialCode: '1876',
    continent_name: 'NA',
  },
  {
    iso2: 'JO',
    name: 'Jordan',
    native: 'الأردن',
    dialCode: '962',
    continent_name: 'AS',
  },
  {
    iso2: 'JP',
    name: 'Japan',
    native: '日本',
    dialCode: '81',
    continent_name: 'AS',
  },
  {
    iso2: 'KE',
    name: 'Kenya',
    native: 'Kenya',
    dialCode: '254',
    continent_name: 'AF',
  },
  {
    iso2: 'KG',
    name: 'Kyrgyzstan',
    native: 'Кыргызстан',
    dialCode: '996',
    continent_name: 'AS',
  },
  {
    iso2: 'KH',
    name: 'Cambodia',
    native: 'Kâmpŭchéa',
    dialCode: '855',
    continent_name: 'AS',
  },
  {
    iso2: 'KI',
    name: 'Kiribati',
    native: 'Kiribati',
    dialCode: '686',
    continent_name: 'OC',
  },
  {
    iso2: 'KM',
    name: 'Comoros',
    native: 'Komori',
    dialCode: '269',
    continent_name: 'AF',
  },
  {
    iso2: 'KN',
    name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
    dialCode: '1869',
    continent_name: 'NA',
  },
  {
    iso2: 'KP',
    name: "Korea, Democratic People's Republic of",
    dialCode: '850',
    native: '북한',
    continent_name: 'AS',
  },
  {
    iso2: 'KR',
    name: 'Korea, Republic of',
    dialCode: '82',
    native: '대한민국',
    continent_name: 'AS',
  },
  {
    iso2: 'KW',
    name: 'Kuwait',
    native: 'الكويت',
    dialCode: '965',
    continent_name: 'AS',
  },
  {
    iso2: 'KY',
    name: 'Cayman Islands',
    native: 'Cayman Islands',
    dialCode: '1345',
    continent_name: 'NA',
  },
  {
    iso2: 'KZ',
    name: 'Kazakhstan',
    native: 'Қазақстан',
    dialCode: '7',
    continent_name: 'AS',
  },
  {
    iso2: 'LA',
    name: "Lao People's Democratic Republic",
    dialCode: '856',
    native: 'ສປປລາວ',
    continent_name: 'AS',
  },
  {
    iso2: 'LB',
    name: 'Lebanon',
    native: 'لبنان',
    dialCode: '961',
    continent_name: 'AS',
  },
  {
    iso2: 'LC',
    name: 'Saint Lucia',
    native: 'Saint Lucia',
    dialCode: '1758',
    continent_name: 'NA',
  },
  {
    iso2: 'LI',
    name: 'Liechtenstein',
    native: 'Liechtenstein',
    dialCode: '423',
    continent_name: 'EU',
  },
  {
    iso2: 'LK',
    name: 'Sri Lanka',
    native: 'śrī laṃkāva',
    dialCode: '94',
    continent_name: 'AS',
  },
  {
    iso2: 'LR',
    name: 'Liberia',
    native: 'Liberia',
    dialCode: '231',
    continent_name: 'AF',
  },
  {
    iso2: 'LS',
    name: 'Lesotho',
    native: 'Lesotho',
    dialCode: '266',
    continent_name: 'AF',
  },
  {
    iso2: 'LT',
    name: 'Lithuania',
    native: 'Lietuva',
    dialCode: '370',
    continent_name: 'EU',
  },
  {
    iso2: 'LU',
    name: 'Luxembourg',
    native: 'Luxembourg',
    dialCode: '352',
    continent_name: 'EU',
  },
  {
    iso2: 'LV',
    name: 'Latvia',
    native: 'Latvija',
    dialCode: '371',
    continent_name: 'EU',
  },
  {
    iso2: 'LY',
    name: 'Libya',
    native: '‏ليبيا',
    dialCode: '218',
    continent_name: 'AF',
  },
  {
    iso2: 'MA',
    name: 'Morocco',
    native: 'المغرب',
    dialCode: '212',
    continent_name: 'AF',
  },
  {
    iso2: 'MC',
    name: 'Monaco',
    native: 'Monaco',
    dialCode: '377',
    continent_name: 'EU',
  },
  {
    iso2: 'MD',
    name: 'Moldova, Republic of',
    dialCode: '373',
    native: 'Moldova',
    continent_name: 'EU',
  },
  {
    iso2: 'ME',
    name: 'Montenegro',
    native: 'Црна Гора',
    dialCode: '382',
    continent_name: 'EU',
  },
  {
    iso2: 'MF',
    name: 'Saint Martin, (French part)',
    dialCode: '590',
    native: 'Saint-Barthélemy',
    continent_name: 'NA',
  },
  {
    iso2: 'MG',
    name: 'Madagascar',
    native: 'Madagasikara',
    dialCode: '261',
    continent_name: 'AF',
  },
  {
    iso2: 'MH',
    name: 'Marshall Islands',
    native: 'M̧ajeļ',
    dialCode: '692',
    continent_name: 'OC',
  },
  {
    iso2: 'MK',
    name: 'North Macedonia',
    native: 'Северна Македонија',
    dialCode: '389',
    continent_name: 'EU',
  },
  {
    iso2: 'ML',
    name: 'Mali',
    native: 'Mali',
    dialCode: '223',
    continent_name: 'AF',
  },
  {
    iso2: 'MM',
    name: 'Myanmar',
    dialCode: '95',
    native: 'မြန်မာ',
    continent_name: 'AS',
  },
  {
    iso2: 'MN',
    name: 'Mongolia',
    native: 'Монгол улс',
    dialCode: '976',
    continent_name: 'AS',
  },
  {
    iso2: 'MO',
    name: 'Macao',
    native: '澳門',
    dialCode: '853',
    continent_name: 'AS',
  },
  {
    iso2: 'MP',
    name: 'Northern Mariana Islands',
    native: 'Northern Mariana Islands',
    dialCode: '1670',
    continent_name: 'OC',
  },
  {
    iso2: 'MQ',
    name: 'Martinique',
    native: 'Martinique',
    dialCode: '596',
    continent_name: 'NA',
  },
  {
    iso2: 'MR',
    name: 'Mauritania',
    native: 'موريتانيا',
    dialCode: '222',
    continent_name: 'AF',
  },
  {
    iso2: 'MS',
    name: 'Montserrat',
    native: 'Montserrat',
    dialCode: '1664',
    continent_name: 'NA',
  },
  {
    iso2: 'MT',
    name: 'Malta',
    native: 'Malta',
    dialCode: '356',
    continent_name: 'EU',
  },
  {
    iso2: 'MU',
    name: 'Mauritius',
    native: 'Maurice',
    dialCode: '230',
    continent_name: 'AF',
  },
  {
    iso2: 'MV',
    name: 'Maldives',
    native: 'Maldives',
    dialCode: '960',
    continent_name: 'AS',
  },
  {
    iso2: 'MW',
    name: 'Malawi',
    native: 'Malawi',
    dialCode: '265',
    continent_name: 'AF',
  },
  {
    iso2: 'MX',
    name: 'Mexico',
    native: 'México',
    dialCode: '52',
    continent_name: 'NA',
  },
  {
    iso2: 'MY',
    name: 'Malaysia',
    native: 'Malaysia',
    dialCode: '60',
    continent_name: 'AS',
  },
  {
    iso2: 'MZ',
    name: 'Mozambique',
    native: 'Moçambique',
    dialCode: '258',
    continent_name: 'AF',
  },
  {
    iso2: 'NA',
    name: 'Namibia',
    native: 'Namibia',
    dialCode: '264',
    continent_name: 'AF',
  },
  {
    iso2: 'NC',
    name: 'New Caledonia',
    native: 'Nouvelle-Calédonie',
    dialCode: '687',
    continent_name: 'OC',
  },
  {
    iso2: 'NE',
    name: 'Niger',
    native: 'Niger',
    dialCode: '227',
    continent_name: 'AF',
  },
  {
    iso2: 'NF',
    name: 'Norfolk Island',
    native: 'Norfolk Island',
    dialCode: '672',
    continent_name: 'OC',
  },
  {
    iso2: 'NG',
    name: 'Nigeria',
    native: 'Nigeria',
    dialCode: '234',
    continent_name: 'AF',
  },
  {
    iso2: 'NI',
    name: 'Nicaragua',
    native: 'Nicaragua',
    dialCode: '505',
    continent_name: 'NA',
  },
  {
    iso2: 'NL',
    name: 'Netherlands',
    native: 'Nederland',
    dialCode: '31',
    continent_name: 'EU',
  },
  {
    iso2: 'NO',
    name: 'Norway',
    native: 'Norge',
    dialCode: '47',
    continent_name: 'EU',
  },
  {
    iso2: 'NP',
    name: 'Nepal',
    native: 'नपल',
    dialCode: '977',
    continent_name: 'AS',
  },
  {
    iso2: 'NR',
    name: 'Nauru',
    native: 'Nauru',
    dialCode: '674',
    continent_name: 'OC',
  },
  {
    iso2: 'NU',
    name: 'Niue',
    native: 'Niuē',
    dialCode: '683',
    continent_name: 'OC',
  },
  {
    iso2: 'NZ',
    name: 'New Zealand',
    native: 'New Zealand',
    dialCode: '64',
    continent_name: 'OC',
  },
  {
    iso2: 'OM',
    name: 'Oman',
    native: 'عمان',
    dialCode: '968',
    continent_name: 'AS',
  },
  {
    iso2: 'PA',
    name: 'Panama',
    native: 'Panamá',
    dialCode: '507',
    continent_name: 'NA',
  },
  {
    iso2: 'PE',
    name: 'Peru',
    native: 'Perú',
    dialCode: '51',
    continent_name: 'SA',
  },
  {
    iso2: 'PF',
    name: 'French Polynesia',
    native: 'Polynésie française',
    dialCode: '689',
    continent_name: 'OC',
  },
  {
    iso2: 'PG',
    name: 'Papua New Guinea',
    native: 'Papua Niugini',
    dialCode: '675',
    continent_name: 'OC',
  },
  {
    iso2: 'PH',
    name: 'Philippines',
    native: 'Pilipinas',
    dialCode: '63',
    continent_name: 'AS',
  },
  {
    iso2: 'PK',
    name: 'Pakistan',
    native: 'Pakistan',
    dialCode: '92',
    continent_name: 'AS',
  },
  {
    iso2: 'PL',
    name: 'Poland',
    native: 'Polska',
    dialCode: '48',
    continent_name: 'EU',
  },
  {
    iso2: 'PM',
    name: 'Saint Pierre and Miquelon',
    native: 'Saint-Pierre-et-Miquelon',
    dialCode: '508',
    continent_name: 'NA',
  },
  {
    iso2: 'PR',
    name: 'Puerto Rico',
    native: 'Puerto Rico',
    dialCode: '1',
    continent_name: 'NA',
  },
  {
    iso2: 'PS',
    name: 'Palestine, State of',
    dialCode: '970',
    native: 'فلسطين',
    continent_name: 'AS',
  },
  {
    iso2: 'PT',
    name: 'Portugal',
    native: 'Portugal',
    dialCode: '351',
    continent_name: 'EU',
  },
  {
    iso2: 'PW',
    name: 'Palau',
    native: 'Palau',
    dialCode: '680',
    continent_name: 'OC',
  },
  {
    iso2: 'PY',
    name: 'Paraguay',
    native: 'Paraguay',
    dialCode: '595',
    continent_name: 'SA',
  },
  {
    iso2: 'QA',
    name: 'Qatar',
    native: 'قطر',
    dialCode: '974',
    continent_name: 'AS',
  },
  {
    iso2: 'RE',
    name: 'Réunion',
    native: 'La Réunion',
    dialCode: '262',
    continent_name: 'AF',
  },
  {
    iso2: 'RO',
    name: 'Romania',
    native: 'România',
    dialCode: '40',
    continent_name: 'EU',
  },
  {
    iso2: 'RS',
    name: 'Serbia',
    native: 'Србија',
    dialCode: '381',
    continent_name: 'EU',
  },
  {
    iso2: 'RU',
    name: 'Russian Federation',
    dialCode: '7',
    native: 'Россия',
    continent_name: 'EU',
  },
  {
    iso2: 'RW',
    name: 'Rwanda',
    native: 'Rwanda',
    dialCode: '250',
    continent_name: 'AF',
  },
  {
    iso2: 'SA',
    name: 'Saudi Arabia',
    native: 'العربية السعودية',
    dialCode: '966',
    continent_name: 'AS',
  },
  {
    iso2: 'SB',
    name: 'Solomon Islands',
    native: 'Solomon Islands',
    dialCode: '677',
    continent_name: 'OC',
  },
  {
    iso2: 'SC',
    name: 'Seychelles',
    native: 'Seychelles',
    dialCode: '248',
    continent_name: 'AF',
  },
  {
    iso2: 'SD',
    name: 'Sudan',
    native: 'السودان',
    dialCode: '249',
    continent_name: 'AF',
  },
  {
    iso2: 'SE',
    name: 'Sweden',
    native: 'Sverige',
    dialCode: '46',
    continent_name: 'EU',
  },
  {
    iso2: 'SG',
    name: 'Singapore',
    native: 'Singapore',
    dialCode: '65',
    continent_name: 'AS',
  },
  {
    iso2: 'SH',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    dialCode: '290',
    native: 'Saint Helena',
    continent_name: 'AF',
  },
  {
    iso2: 'SI',
    name: 'Slovenia',
    native: 'Slovenija',
    dialCode: '386',
    continent_name: 'EU',
  },
  {
    iso2: 'SJ',
    name: 'Svalbard and Jan Mayen',
    native: 'Svalbard og Jan Mayen',
    dialCode: '47',
    continent_name: 'EU',
  },
  {
    iso2: 'SK',
    name: 'Slovakia',
    native: 'Slovensko',
    dialCode: '421',
    continent_name: 'EU',
  },
  {
    iso2: 'SL',
    name: 'Sierra Leone',
    native: 'Sierra Leone',
    dialCode: '232',
    continent_name: 'AF',
  },
  {
    iso2: 'SM',
    name: 'San Marino',
    native: 'San Marino',
    dialCode: '378',
    continent_name: 'EU',
  },
  {
    iso2: 'SN',
    name: 'Senegal',
    native: 'Sénégal',
    dialCode: '221',
    continent_name: 'AF',
  },
  {
    iso2: 'SO',
    name: 'Somalia',
    native: 'Soomaaliya',
    dialCode: '252',
    continent_name: 'AF',
  },
  {
    iso2: 'SR',
    name: 'Suriname',
    dialCode: '597',
    native: 'Suricountry_name',
    continent_name: 'SA',
  },
  {
    iso2: 'SS',
    name: 'South Sudan',
    native: 'South Sudan',
    dialCode: '211',
    continent_name: 'AF',
  },
  {
    iso2: 'ST',
    name: 'Sao Tome and Principe',
    dialCode: '239',
    native: 'São Tomé e Príncipe',
    continent_name: 'AF',
  },
  {
    iso2: 'SV',
    name: 'El Salvador',
    native: 'El Salvador',
    dialCode: '503',
    continent_name: 'NA',
  },
  {
    iso2: 'SX',
    name: 'Sint Maarten, (Dutch part)',
    dialCode: '1721',
    native: 'Sint Maarten',
    continent_name: 'NA',
  },
  {
    iso2: 'SY',
    name: 'Syrian Arab Republic',
    dialCode: '963',
    native: 'سوريا',
    continent_name: 'AS',
  },
  {
    iso2: 'SZ',
    name: 'Eswatini',
    dialCode: '268',
    native: 'Swaziland',
    continent_name: 'AF',
  },
  {
    iso2: 'TC',
    name: 'Turks and Caicos Islands',
    native: 'Turks and Caicos Islands',
    dialCode: '1649',
    continent_name: 'NA',
  },
  {
    iso2: 'TD',
    name: 'Chad',
    native: 'Tchad',
    dialCode: '235',
    continent_name: 'AF',
  },
  {
    iso2: 'TG',
    name: 'Togo',
    native: 'Togo',
    dialCode: '228',
    continent_name: 'AF',
  },
  {
    iso2: 'TH',
    name: 'Thailand',
    native: 'ประเทศไทย',
    dialCode: '66',
    continent_name: 'AS',
  },
  {
    iso2: 'TJ',
    name: 'Tajikistan',
    native: 'Тоҷикистон',
    dialCode: '992',
    continent_name: 'AS',
  },
  {
    iso2: 'TK',
    name: 'Tokelau',
    native: 'Tokelau',
    dialCode: '690',
    continent_name: 'OC',
  },
  {
    iso2: 'TL',
    name: 'Timor-Leste',
    dialCode: '670',
    native: 'Timor-Leste',
    continent_name: 'OC',
  },
  {
    iso2: 'TM',
    name: 'Turkmenistan',
    native: 'Türkmenistan',
    dialCode: '993',
    continent_name: 'AS',
  },
  {
    iso2: 'TN',
    name: 'Tunisia',
    native: 'تونس',
    dialCode: '216',
    continent_name: 'AF',
  },
  {
    iso2: 'TO',
    name: 'Tonga',
    native: 'Tonga',
    dialCode: '676',
    continent_name: 'OC',
  },
  {
    iso2: 'TR',
    name: 'Turkey',
    native: 'Türkiye',
    dialCode: '90',
    continent_name: 'AS',
  },
  {
    iso2: 'TT',
    name: 'Trinidad and Tobago',
    native: 'Trinidad and Tobago',
    dialCode: '1868',
    continent_name: 'NA',
  },
  {
    iso2: 'TV',
    name: 'Tuvalu',
    native: 'Tuvalu',
    dialCode: '688',
    continent_name: 'OC',
  },
  {
    iso2: 'TW',
    name: 'Taiwan, Province of China',
    dialCode: '886',
    native: '臺灣',
    continent_name: 'AS',
  },
  {
    iso2: 'TZ',
    name: 'Tanzania, United Republic of',
    dialCode: '255',
    native: 'Tanzania',
    continent_name: 'AF',
  },
  {
    iso2: 'UA',
    name: 'Ukraine',
    native: 'Україна',
    dialCode: '380',
    continent_name: 'EU',
  },
  {
    iso2: 'UG',
    name: 'Uganda',
    native: 'Uganda',
    dialCode: '256',
    continent_name: 'AF',
  },
  {
    iso2: 'US',
    name: 'United States of America',
    dialCode: '1',
    native: 'United States',
    continent_name: 'NA',
  },
  {
    iso2: 'UY',
    name: 'Uruguay',
    native: 'Uruguay',
    dialCode: '598',
    continent_name: 'SA',
  },
  {
    iso2: 'UZ',
    name: 'Uzbekistan',
    native: 'O‘zbekiston',
    dialCode: '998',
    continent_name: 'AS',
  },
  {
    iso2: 'VA',
    name: 'Holy See',
    dialCode: '39',
    native: 'Santa Sede',
    continent_name: 'EU',
  },
  {
    iso2: 'VC',
    name: 'Saint Vincent and the Grenadines',
    native: 'Saint Vincent and the Grenadines',
    dialCode: '1784',
    continent_name: 'NA',
  },
  {
    iso2: 'VE',
    name: 'Venezuela, Bolivarian Republic of',
    dialCode: '58',
    native: 'Venezuela',
    continent_name: 'SA',
  },
  {
    iso2: 'VG',
    name: 'Virgin Islands, British',
    dialCode: '1284',
    native: 'British Virgin Islands',
    continent_name: 'NA',
  },
  {
    iso2: 'VI',
    name: 'Virgin Islands, U.S.',
    dialCode: '1340',
    native: 'United States Virgin Islands',
    continent_name: 'NA',
  },
  {
    iso2: 'VN',
    name: 'Viet Nam',
    dialCode: '84',
    native: 'Việt Nam',
    continent_name: 'AS',
  },
  {
    iso2: 'VU',
    name: 'Vanuatu',
    native: 'Vanuatu',
    dialCode: '678',
    continent_name: 'OC',
  },
  {
    iso2: 'WF',
    name: 'Wallis and Futuna',
    native: 'Wallis et Futuna',
    dialCode: '681',
    continent_name: 'OC',
  },
  {
    iso2: 'WS',
    name: 'Samoa',
    native: 'Samoa',
    dialCode: '685',
    continent_name: 'OC',
  },
  {
    iso2: 'YE',
    name: 'Yemen',
    native: 'اليَمَن',
    dialCode: '967',
    continent_name: 'AS',
  },
  {
    iso2: 'YT',
    name: 'Mayotte',
    native: 'Mayotte',
    dialCode: '262',
    continent_name: 'AF',
  },
  {
    iso2: 'ZA',
    name: 'South Africa',
    native: 'South Africa',
    dialCode: '27',
    continent_name: 'AF',
  },
  {
    iso2: 'ZM',
    name: 'Zambia',
    native: 'Zambia',
    dialCode: '260',
    continent_name: 'AF',
  },
  {
    iso2: 'ZW',
    name: 'Zimbabwe',
    native: 'Zimbabwe',
    dialCode: '263',
    continent_name: 'AF',
  },
];
